### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by GSaksham97** [INFO-526-F24/project-01-Uchihas#16]
The following is the peer review of the project proposal by [pacman]. The team members that participated in this review are 

- [Vaishnavi Kulkarni] - @[Vaishnavi-K23]
- [Saksham Gupta] - @[GSaksham97
- [Ralph Dsouza] - @[RD0410]
- ...

- Describe the goal of the project.
According to the proposal, the goal of their project is to investigate the impact of NO2 concentration on hospital admissions and the relationship between floodplain extent and housing density in Pittsburgh, PA, using multiple datasets.

- Describe the data used or collected.
The data used for this project is sourced from the EPA’s BenMAP program and includes 1089 observations across 15 variables. It focuses on air quality (e.g., NO2 levels) and health outcomes such as hospital admissions for respiratory conditions.

- Describe how the research question will be answered, e.g. what approaches/methods will be used.
They will clean the dataset first then visualize the NO2-hospital admissions relationship using scatter plots and heatmaps, and apply linear regression to assess the impact of NO2 on hospital admissions, adjusting for demographic controls.

- Is there anything that is unclear from the proposal?
According to me the proposal is clear and well-structured. In Research Question 2, the proposal mentions merging floodplain data but doesn't specify how floodplain exposure will be classified. How will the extent of exposure (e.g., low, moderate, high) be categorized for analysis?

- Provide constructive feedback on how the team might be able to improve their project.
The proposal would benefit from a clear strategy for handling missing data. Will missing values be imputed, or will rows be removed? Specify how floodplain exposure will be categorized (e.g., low, high).

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested in the relationship between environmental factors (NO2 levels, floodplains) and their impact on public health and housing density. Highlighting how air pollution (NO2) directly affects hospital admissions and how floodplain zones influence housing patterns will be crucial for understanding the broader implications for urban planning and public health.

- Provide constructive feedback on any issues with file and/or code organization.
According to me there are no issues with file.

- (Optional) Any further comments or feedback?
No further comments. The proposal is well structured.

**Comment by wasnikh0** [comment]
Thanks for the review
