### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by HitarthBharad** [INFO-526-F24/project-01-Uchihas#17]
The following is the peer review of the project proposal by VIZards. The team members that participated in this review are 

1. Hitarth Bharad - @HitarthBharad
2. Ashwini Jannu - @AshwiniJannu
3. Mridula Kalaiselvan -@mridula237
4. Lekhashree Honnavalli Jayarama -@lekhashree03
5. Dhawal Gajwe - @billDhawal
6. Hardik Chemburkar - @TRENCHhardik2042

**- Describe the goal of the project.**
Project aims to investigate the impact of NO2 concentration on hospital admissions and the relationship between floodplain extent and housing density in Pittsburgh, PA.

**- Describe the data used or collected.**
This dataset is sourced from the EPA’s BenMAP program. It is combination of 3 datasets. These datasets provide the view of the environmental and demographic factors influencing Pittsburgh’s communities. 

**- Describe how the research question will be answered, e.g. what approaches / methods will be used.**
_Question 1_: How does the concentration of NO2 impact the rate of hospital admissions for respiratory conditions across different block groups in Pittsburgh, PA?
_Approach:_  This analysis examines the impact of NO₂ concentration on respiratory-related hospital admissions across Pittsburgh’s block groups. It includes visualizations and a linear regression model adjusted for demographic controls to assess the relationship.

_Question 2:_ How does the extent of land in floodplain zones affect housing density across different block groups in Pittsburgh, PA?
_Approach_: This analysis investigates the impact of floodplain extent on housing density across Pittsburgh’s block groups. It includes visualizations and a linear regression model with potential interaction terms to examine urban-suburban differences.

**- Is there anything that is unclear from the proposal?**

1. Project Title: Update the title to align more closely with the project’s objectives.
2. Abstract Clarity: Revise the abstract to clearly outline the research purpose, objectives, and expected outcomes.
3. Dataset Relationships: Explain how the three datasets interact to support the analysis.
4. Research Question Integration: Highlight the interconnections between research questions to enhance analytical depth.

**- Provide constructive feedback on how the team might be able to improve their project.**

1. Project title needs to be allied with proposed research questions.
2. Provide a brief explanation of how each dataset contributes to answering the research questions. Identifying key connections between data sources  will help clarify the project’s methodology and improve its analytical foundation.

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
This project is compelling in its examination of how environmental factors, specifically NO₂ levels and floodplain extent, affect housing density across Pittsburgh. By mapping these relationships, the study sheds light on potential vulnerabilities within various block groups, offering insights that could guide urban planning and public health interventions. 

**- Provide constructive feedback on any issues with file and/or code organization.**
Improving the formatting and use of bullet points vs numbered points will enhance readability and organization, making it easier for readers to follow key points. Clear, well-structured bullet points can emphasize critical insights and improve the overall flow of the document, aiding in a more professional presentation.

**- (Optional) Any further comments or feedback?**
The project’s ideas could be articulated more clearly. Focusing on concise language and cohesive structure will help communicate the research objectives, methodology, and anticipated outcomes more effectively.

**Comment by wasnikh0** [comment]
closed
